# 端口
server:
  port: 8888

spring:
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
          # 使用小写service-id
          lower-case-service-id: true


