# 端口
server:
  port: 8888

spring:
  application:
    name:
      mall-gateway
  config:
    import:
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.152:8848   # Nacos 地址
        username: nacos                   # 默认账号
        password: nacos                   # 默认密码
        namespace: mall                   # 命名空间ID，默认""
      config:
        server-addr: 192.168.1.152:8848   # Nacos 地址
        username: nacos                   # 默认账号
        password: nacos                   # 默认密码
        namespace: mall                   # 命名空间ID，默认""
        file-extension: yaml              # 配置文件扩展名(可选)，配置内容文件的数据格式，默认值：properties
        group: DEFAULT_GROUP              # 默认分组(可选)
        refresh-enabled: true  # 可选：启用动态刷新
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
          # 使用小写service-id
          lower-case-service-id: true
  data:
    redis:
      host: 192.168.1.170     # Redis 服务器地址
      port: 6379           # Redis 端口
  #    password: 123456     # Redis 密码（如果没有密码，可以省略）
      database: 1          # 使用的 Redis 数据库索引（默认 0）

# 日志记录输出配置
logging:
  level:
    root: debug
