# 端口
server:
  port: 10040

spring:
  application:
    name:
      mall-ware
  config:
    import:
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.152:8848   # Nacos 地址
        username: nacos                   # 默认账号
        password: nacos                   # 默认密码
        namespace: mall                   # 命名空间ID，默认""
      config:
        server-addr: 192.168.1.152:8848   # Nacos 地址
        username: nacos                   # 默认账号
        password: nacos                   # 默认密码
        namespace: mall                   # 命名空间ID，默认""
        file-extension: yaml              # 配置文件扩展名(可选)，配置内容文件的数据格式，默认值：properties
        group: DEFAULT_GROUP              # 默认分组(可选)
        refresh-enabled: true  # 可选：启用动态刷新
  datasource:
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.170:3306/mall_wms?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456


 # 日志记录输出配置
logging:
  level:
    root: debug
