# 端口
server:
  port: 9000


spring:
  application:
    name:
      mall-order
  config:
    import:
      - optional:nacos:${spring.application.name}
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.152:8848
        username: nacos
        password: nacos
      config:
        server-addr: 192.168.1.152:8848
        username: nacos
        password: nacos
        file-extension: yaml              # 配置内容文件的数据格式，默认值：properties
  datasource:
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.170:3306/mall_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456


 # 日志记录输出配置
logging:
  level:
    root: debug
